version: '3'

services:
  database:
    image: mariadb
    networks:
     - default
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
  cache:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
